main:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: "{{ env_var('DBT_PASSWORD') }}"
      dbname: dev-dbt
      schema: dev
      threads: 6
    prod:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: "{{ env_var('DBT_PASSWORD') }}"
      dbname: prod-dbt
      schema: public
      threads: 6
